### ISSUE TITLE
Installing Docker does not include VBoxManage

### ISSUE THREAD

**Issue by thien-do** [anduintransaction/anduin-kube#5]
**Issue:**

When the script sees that `VBoxManage` is not available then [it tells user to download Docker Toolbox](https://github.com/anduintransaction/anduin-kube/blob/master/lib/functions/install.sh#L5).

However, Docker Toolbox is [deprecated](https://docs.docker.com/toolbox/) and replaced by Docker for Mac and Docker for Windows. The url mentioned is also redirected to https://www.docker.com/get-docker which has links to above two.

More importantly, after installing Docker for Mac, the `VBoxManage` is still not available.

However, install VirtualBox does help resolve this issue (`VBoxManage` is then available).

**Question:**

- Why does the script instructed to install Docker when `VBoxManage` is not available? (Maybe because Docker Toolbox did include `VBoxManage` in the past?)
- Should we update the instruction to suggest installing VirtualBox or the new Docker app (Docker for Mac or Docker for Windows)?

**Comment by keimoon** [comment]
Should be fixed in https://github.com/anduintransaction/anduin-kube/commit/1aaec238a9805291aad6e176a13bd7c78b95b3c3
